### ISSUE TITLE
No module 'zk'

### ISSUE THREAD

**Issue by iMoshi** [frappe/push-biometric-erpnext#4] opened 2019-12-09 04:51 UTC
Thank you so much for the script, but I'm often getting error:

```
Traceback (most recent call last):
  File "push_to_erpnext.py", line 12, in <module>
    from zk import ZK, const
ModuleNotFoundError: No module named 'zk'
```

I've installed the script in root directory, logs show it worked until midnight. I've then installed the script in bench directory, and logs tell me 

```
Traceback (most recent call last):
  File "push_to_erpnext.py", line 59, in main
    update_shift_last_sync_timestamp(config.shift_type_device_mapping)
  File "push_to_erpnext.py", line 212, in update_shift_last_sync_timestamp
    if min_pull_timestamp > sync_current_timestamp:
TypeError: '>' not supported between instances of 'datetime.datetime' and 'NoneType'
```

Is there a further configuration that I'm missing?

**Comment by karthikeyan5** [comment] 2019-12-14 06:15
> Traceback (most recent call last):
>   File "push_to_erpnext.py", line 59, in main
>     update_shift_last_sync_timestamp(config.shift_type_device_mapping)
>   File "push_to_erpnext.py", line 212, in update_shift_last_sync_timestamp
>     if min_pull_timestamp > sync_current_timestamp:
> TypeError: '>' not supported between instances of 'datetime.datetime' and 'NoneType'

@iMoshi, this part was a bug indeed... this has now been fixed in https://github.com/frappe/push-biometric-erpnext/commit/58d5dec30db254400e8fc5c0fa9bb78236366fca

Please pull the latest version and try again...

**Comment by karthikeyan5** [comment] 2019-12-14 06:19
> Traceback (most recent call last):
>   File "push_to_erpnext.py", line 12, in <module>
>     from zk import ZK, const
> ModuleNotFoundError: No module named 'zk'

this one seems to be a problem with your dependencies. 

`pip install -r requirements.txt` should probably fix it... 

please share reproduction steps if you continue to face this problem...

**Closed by karthikeyan5** 2019-12-14 06:19 UTC

**Comment by iMoshi** [comment] 2019-12-15 03:21
Gotcha. Thank you so much guys, gonna try again on Monday when I get to work :)

**Comment by AidosAkhmetov** [comment] 2021-05-25 08:39
zkconst library is from zklib?

**Comment by zahra6971** [comment] 2023-01-16 09:02
> > Traceback (most recent call last):
> > File "push_to_erpnext.py", line 12, in 
> > from zk import ZK, const
> > ModuleNotFoundError: No module named 'zk'
> 
> this one seems to be a problem with your dependencies.
> 
> `pip install -r requirements.txt` should probably fix it...
> 
> please share reproduction steps if you continue to face this problem...


Dear @karthikeyan5 ,  
I have this error, actually, when I run "python erpnext_sync_win.py install", I had an error "ModuleNotFoundError: No module named 'requests'" then I used "pip install requests" and run "python erpnext_sync_win.py install" again then I have another error "ModuleNotFoundError: No module named 'pickledb" after that I run "python erpnext_sync_win.py install"  again, this time it errors "ModuleNotFoundError: No module named 'zk'"
by using "pip install zk "I tried to install the zk, but when I run "python erpnext_sync_win.py install", I have this error again "ModuleNotFoundError: No module named 'zk'". Would you please tell me what I can do?

**Comment by hashimdreamzz** [comment] 2023-02-02 06:26
@zahra6971 Use     `python3 -m pip install Pyzk --upgrade`
